### ISSUE TITLE
Showing registers (buffers, tabs)

### ISSUE THREAD

**Issue by bssstudio** [lunixbochs/actualvim#10]
When `:reg` all of the contents are displayed line by line (very fast) in the bottom (status) line, effectively preventing from reading register values.

This is also an issue with other commands (listing buffers, tabs, ...)

**Comment by divinites** [comment]
I share the same problem... do you still plan to develop actual vim with NeoVim?

**Comment by lunixbochs** [comment]
closing in favor of #39
