### ISSUE TITLE
View doesn't update after command

### ISSUE THREAD

**Issue by xelra** [lunixbochs/ActualVim#104]
I'm having the issue again with ActualVim that it doesn't update the view. When I'm pressing `i` for example, the curor will still be a block and only on the second input will it show the input and the cursor will change. It's especially apparent when pressing `o`, because the newline won't appear until another key is pressed. The same thing happen when pressing `esc`, the cursor will only return to being a block after pressing something after.

**Comment by lunixbochs** [comment]
did you update to neovim 0.2?

**Comment by xelra** [comment]
```
C:\Users\xelra>nvim --version
NVIM v0.2.0-788-gb2b15e6e
```
I'm gonna try update to the latest Neovim too.

**Comment by lunixbochs** [comment]
If the async branch fixes this, you can try rebasing it onto master to get the best of both worlds:

```
git checkout async
git rebase master
```

Take the HEAD side of the resulting conflict verbatim:

```
<<<<<<< HEAD
            if self.nvim_mode:
                res = self.nv.request('nvim_get_mode') or {}
                ready = not res.get('blocking', True)
=======
            if self.nvim_mode and False:
                _, blocked = self.nv.request('nvim_get_mode')
                ready = not blocked
>>>>>>> more reliable async readiness check
```

This should prevent any keystrokes from ever being dropped.

**Comment by xelra** [comment]
After upgrading to `NVIM v0.2.1-193-gdc8a45dc` I'm not seeing the issue anymore.

I'm really excited to finally getting work done with Sublime+ActualVim. Now I'm off to testing the autocompletion and popup stuff.
