### ISSUE TITLE
Is it possible to create Sublime keymaps based on the Vim mode?

### ISSUE THREAD

**Issue by valrus** [lunixbochs/ActualVim#105]
Hopefully the title is clear, but if not, I'm talking about a .sublime-keymap entry like the following (NeoVintageous) one:

```
{"keys": ["escape"], "command": "_enter_normal_mode", "args": {"mode": "mode_insert"}, "context": [{"key": "vi_insert_mode_aware"}]}
```

In particular, I guess I'm asking whether there's an equivalent of the "context" part of that. Or, alternatively, is there any way to trigger Sublime commands (e.g. mapping some command to Ctrl-P) from .vimrc?

**Comment by lunixbochs** [comment]
Here's an example:

```
{ "keys": ["ctrl+s"], "context": [{"key": "setting.actual_mode", "operand": true}],  "command": "actual_disable"},
{ "keys": ["ctrl+s"], "context": [{"key": "setting.actual_mode", "operand": false}], "command": "actual_enable"},
```

You can bind something to ^P as long as it's not a vim keybinding. I don't have a way to trigger sublime commands from vim yet, but that's a good idea.

If you do use sublime mode, you can set a different theme for sublime and vim so it's easier to keep track. Take a look at the actualvim user settings.

**Comment by valrus** [comment]
That gets me halfway there, but the bindings are in effect regardless of the Vim mode (i.e. they happen in either insert or normal mode, whereas I maybe want them only in normal mode).

**Comment by lunixbochs** [comment]
In your actualvim user settings under settings.vim.modes.normal you can add something like `"actualvim_normal_mode": true` (which will be set on the view when you enter normal mode, and unset when you're in any other vim mode, including "sublime" mode). Then add `{"key": "setting.actualvim_normal_mode", "operand": true}` as another context to the disable keybinding.

**Comment by lunixbochs** [comment]
Done in eb676f992aa08e1c08b9c2133a7acbaab5c02346

Example key binding:
```
{"keys": ["shift+f1"],
 "command": "paste",
 "context": [{"key": "setting.av:mode:normal", "operand": true}]},
```

Mode names:

- normal
- command
- insert
- replace
- visual
- visual_line
- visual_block

As well as aggregate modes `inserts` and `visuals`.
