### ISSUE TITLE
zz zb zt shortcuts not working

### ISSUE THREAD

**Issue by tonatiuh** [lunixbochs/ActualVim#111]
In vim/visual mode if you press:

- zt moves the cursor and the file vertically to the top of the screen
- zz moves the cursor and the file vertically to the center of the screen
- zb moves the cursor and the file vertically to the bottom of the screen

Is there any chance this can be added to ActualVim? 
I wonder why is that it doesn't work automatically?

Awesome plugin btw, thanks! 🥇

**Comment by lunixbochs** [comment]
Viewports aren't synced. There's an issue about the cursor for this.

**Comment by kevinw** [comment]
Seconding this feature...I use zt, zz, and zb to scroll constantly, and it's a sorely missing feature from ActualVim. Thanks for the hard work!

**Comment by darluc** [comment]
ctrl-e ctrl-y are not working either

**Comment by lunixbochs** [comment]
Fixed, release pending.
