### ISSUE TITLE
Don't recognize filetype with extension

### ISSUE THREAD

**Issue by ghost** [lunixbochs/ActualVim#114]
For exemple, when opening a .py file, the filetype isn't set at python by default. You have to do it by hand (```set ft=pyhton```).

You can see it by testing automatic indentation (for example after ```:``` in python), ```commentstring``` and so for...

PS: thank for this plugin! It's wonderfull.

**Comment by lunixbochs** [comment]
Will look into this soon. https://github.com/jamessan/vim-gnupg/blob/master/plugin/gnupg.vim#L607-L629 for my reference from neovim devs

**Comment by lunixbochs** [comment]
fixed in f5821cc689bc58d3912717b5907263d4c4f91e6d, will be in 0.9.15 release
