### ISSUE TITLE
Donate for port to another editor

### ISSUE THREAD

**Issue by Alexey-T** [lunixbochs/ActualVim#116]
Hello,
Can I make you donation to port ActualVim to CudaText editor?
Thanks in advance...

**Comment by lunixbochs** [comment]
It looks possible. Depends on the donation, as it might be a bit of work (especially if I maintain it).

**Comment by Alexey-T** [comment]
Good... Maybe 30-50$ for the first release? what do you think?

**Comment by lunixbochs** [comment]
I don't have the time to maintain another port of it at this time. If you find someone willing to do a port, I can offer minor assistance and share the design details I shared with the VSCodeVim project.
