### ISSUE TITLE
Cursor position after paste with system clipboard

### ISSUE THREAD

**Issue by mjedmonds** [lunixbochs/ActualVim#118]
The cursor position does not match the visual cursor after pasting from the system clipboard.

To repeat:
1. Copy something
2. Paste (in normal or insert mode)

The cursor will appear at the end of the paste, but in reality, it is in the previous position before the paste (i.e. the first character of the paste).

I'm on macOS, if that matters.

**Comment by lunixbochs** [comment]
I think Sublime's paste needs to be intercepted to fix selection to Vim and fix this.

**Comment by lunixbochs** [comment]
Fixed in 098d02a62e5ba5f7cbdcfadfa5e7986db7527873, pending release.
