### ISSUE TITLE
True block shape in normal mode

### ISSUE THREAD

**Issue by navdeepio** [lunixbochs/ActualVim#122]
In my opinion, the current block looks ugly with the highlighted underscore beneath, can we not have a proper block similar to neovim?

**Comment by lunixbochs** [comment]
ActualVim already sets a block cursor where appropriate. Whether the block is filled in or an underscore is entirely controlled by your color scheme: https://stackoverflow.com/a/31308818/293352

**Comment by navdeepio** [comment]
@lunixbochs  I understand you could change the cursor shape in the insert mode using a theme of your choice, but what about normal mode?

**Comment by lunixbochs** [comment]
I'm talking about normal mode. Blink can be disabled by the global setting `"caret_style": "solid"`, and your active color scheme controls the exact color of the underline and of the block.

Read the style in the link, and try different color schemes (NOT themes) or modify one to suit your preference if necessary. This is what it looks like in my current color scheme:

![solid](https://user-images.githubusercontent.com/117642/30759498-4071c3e4-9f8b-11e7-97f9-24eb4019d2f0.png)
