### ISSUE TITLE
Sublime as Insert Mode -- Lost!

### ISSUE THREAD

**Issue by cerenziam** [lunixbochs/ActualVim#125]
When I first installed neovim/ActualVim, Sublime would take over when in Insert Mode (by default). This scenario is in fact ideal to me, so I can benefit from my other Sublime extensions quickly. But some time while I was toying around with Vim by upgrading my .vimrc file and adding packages, and then applying them to nvim by symlinking, the scenario above that I thought was default (and amazing) disappeared! I've tried reading other posts concerning related issues, but can't yet figure out how to get back to that ideal state :(.

**Comment by lunixbochs** [comment]
> Sublime would take over when in Insert Mode

This is indeed ideal, but was never quite the case. You'll need to describe more what you could do before, and what happens incorrectly when you do it now for me to diagnose.

**Comment by cerenziam** [comment]
Thanks for the quick reply -- I'm sure you're right, but I'm completely flummoxed about how I had the functionality available to me for days last week. I even took note of what I did and sent it to two friends in case they were interested, but I just followed those same steps on a spare mac, and indeed I do not gain this functionality. This leads me to believe my "losing" it had nothing to do with any configuring I was doing yesterday. I guess I must've been toggling it somehow, but I'm surprised I wouldn't notice something like that.

**Comment by lunixbochs** [comment]
You can bind a key to toggle by adding a user keymap like this:
```
    { "keys": ["ctrl+s"], "context": [{"key": "setting.actual_mode", "operand": true}],  "command": "actual_disable"},
    { "keys": ["ctrl+s"], "context": [{"key": "setting.actual_mode", "operand": false}], "command": "actual_enable"},
```

**Comment by cerenziam** [comment]
That does indeed work (and good to know, thanks) but definitely was not required for me before. The only other thing I can think of is that I was instead using the so-called Vintage mode, but I don't recall ever installing that. I guess we can close this and I'll let you know if I ever reproduce the scenario I had before.
