### ISSUE TITLE
ImportError: No module named 'ActualVim'

### ISSUE THREAD

**Issue by vinturisvalentin** [lunixbochs/ActualVim#139]
ActualVim doesn't start when restarting subl3 on Antergos Linux, version 4.14.11-1-ARCH. SublimeText, ActualVim and NeoVim are all freshly installed.
Here's the console log:

`startup, version: 3143 linux x64 channel: stable`
`executable: /opt/sublime_text_3/sublime_text`
`working dir: /home/neon`
`packages path: /home/neon/.config/sublime-text-3/Packages`
`state path: /home/neon/.config/sublime-text-3/Local`
`zip path: /opt/sublime_text_3/Packages`
`zip path: /home/neon/.config/sublime-text-3/Installed Packages`
`ignored_packages: ["Vintage"]`
`pre session restore time: 0.097377`
`startup time: 0.214517`
`first paint time: 0.223858`
`reloading plugin Default.auto_indent_tag`
`reloading plugin Default.block`
`reloading plugin Default.comment`
`reloading plugin Default.convert_syntax`
`reloading plugin Default.copy_path`
`reloading plugin Default.delete_word`
`reloading plugin Default.detect_indentation`
`reloading plugin Default.duplicate_line`
`reloading plugin Default.echo`
`reloading plugin Default.exec`
`reloading plugin Default.fold`
`reloading plugin Default.font`
`reloading plugin Default.goto_line`
`reloading plugin Default.history_list`
`reloading plugin Default.indentation`
`reloading plugin Default.install_package_control`
`reloading plugin Default.kill_ring`
`reloading plugin Default.mark`
`reloading plugin Default.new_templates`
`reloading plugin Default.open_context_url`
`reloading plugin Default.open_in_browser`
`reloading plugin Default.pane`
`reloading plugin Default.paragraph`
`reloading plugin Default.paste_from_history`
`reloading plugin Default.profile`
`reloading plugin Default.quick_panel`
`reloading plugin Default.run_syntax_tests`
`reloading plugin Default.save_on_focus_lost`
`reloading plugin Default.scroll`
`reloading plugin Default.set_unsaved_view_name`
`reloading plugin Default.settings`
`reloading plugin Default.show_scope_name`
`reloading plugin Default.side_bar`
`reloading plugin Default.sort`
`reloading plugin Default.swap_line`
`reloading plugin Default.switch_file`
`reloading plugin Default.symbol`
`reloading plugin Default.transform`
`reloading plugin Default.transpose`
`reloading plugin Default.trim_trailing_white_space`
`reloading plugin Default.ui`
`reloading plugin CSS.css_completions`
`reloading plugin Diff.diff`
`reloading plugin HTML.encode_html_entities`
`reloading plugin HTML.html_completions`
`reloading plugin actualvim.actual`
`Traceback (most recent call last):`
`  File "/opt/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin`
`    m = importlib.import_module(modulename)`
`  File "./python3.3/importlib/__init__.py", line 90, in import_module`
`  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper`
`  File "<frozen importlib._bootstrap>", line 1022, in load_module`
`  File "<frozen importlib._bootstrap>", line 1003, in load_module`
`  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper`
`  File "<frozen importlib._bootstrap>", line 868, in _load_module`
`  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/actual.py", line 6, in <module>`
`    from .view import ActualVim`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/view.py", line 7, in <module>`
`    from . import neo`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/neo.py", line 10, in <module>`
`    from .lib import neovim`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/__init__.py", line 8, in <module>`
`    from .api import Nvim`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/__init__.py", line 7, in <module>`
`    from .buffer import Buffer`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/buffer.py", line 2, in <module>`
`    from .common import Remote`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/common.py", line 4, in <module>`
`    from ActualVim.lib import msgpack`
`ImportError: No module named 'ActualVim'`
`reloading plugin actualvim.edit`
`reloading plugin actualvim.neo`
`Traceback (most recent call last):`
`  File "/opt/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin`
`    m = importlib.import_module(modulename)`
`  File "./python3.3/importlib/__init__.py", line 90, in import_module`
`  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper`
`  File "<frozen importlib._bootstrap>", line 1022, in load_module`
`  File "<frozen importlib._bootstrap>", line 1003, in load_module`
`  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper`
`  File "<frozen importlib._bootstrap>", line 868, in _load_module`
`  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/neo.py", line 10, in <module>`
`    from .lib import neovim`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/__init__.py", line 8, in <module>`
`    from .api import Nvim`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/__init__.py", line 7, in <module>`
`    from .buffer import Buffer`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/buffer.py", line 2, in <module>`
`    from .common import Remote`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/common.py", line 4, in <module>`
`    from ActualVim.lib import msgpack`
`ImportError: No module named 'ActualVim'`
`reloading plugin actualvim.screen`
`reloading plugin actualvim.settings`
`reloading plugin actualvim.view`
`Traceback (most recent call last):`
`  File "/opt/sublime_text_3/sublime_plugin.py", line 109, in reload_plugin`
`    m = importlib.import_module(modulename)`
`  File "./python3.3/importlib/__init__.py", line 90, in import_module`
`  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper`
`  File "<frozen importlib._bootstrap>", line 1022, in load_module`
`  File "<frozen importlib._bootstrap>", line 1003, in load_module`
`  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper`
`  File "<frozen importlib._bootstrap>", line 868, in _load_module`
`  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/view.py", line 7, in <module>`
`    from . import neo`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/neo.py", line 10, in <module>`
`    from .lib import neovim`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/__init__.py", line 8, in <module>`
`    from .api import Nvim`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/__init__.py", line 7, in <module>`
`    from .buffer import Buffer`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/buffer.py", line 2, in <module>`
`    from .common import Remote`
`  File "/home/neon/.config/sublime-text-3/Packages/actualvim/lib/neovim/api/common.py", line 4, in <module>`
`    from ActualVim.lib import msgpack`
`ImportError: No module named 'ActualVim'`
`plugins loaded`

**Comment by lunixbochs** [comment]
`/home/neon/.config/sublime-text-3/Packages/actualvim` this is wrong, I renamed it to uppercase a long time ago. How did you install it with a lowercase name?

**Comment by vinturisvalentin** [comment]
Weird. I just used `git clone`. Works correctly now.

**Comment by vinturisvalentin** [comment]
Weird. I just used `git clone`. Works correctly now.
