### ISSUE TITLE
dw doesn't work with neovim 0.2.0 but works with 0.2.2 

### ISSUE THREAD

**Issue by brianc118** [lunixbochs/ActualVim#142]
Tried running delete word with _dw_ but didn't work with neovim 0.2.0. Updated to 0.2.2 and it worked. I'm on MacOS High Sierra with ST3156 and the latest version of ActualVim. Is this a known problem? May be beneficial to add in the README.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/commit/541dde36e3302314e2646415dbfd2b79a6c2a1fc fixed the core issue starting with 0.2.1.

**Comment by lunixbochs** [comment]
I added neovim version recommendation in readme, closing.
