### ISSUE TITLE
c-y or scroll up not working

### ISSUE THREAD

**Issue by bkyam** [lunixbochs/ActualVim#149]
First off, I love this tool you built. Thank you so much for creating and maintaining it.  I'm a loooong time Vim user and have been thrust into a work environment where working in Sublime is useful for various reasons. So this tool is quite helpful.

One issue I'm having is that ctrl+y doesn't work for me.  Any help would be appreciated.

Here's what I have set up...

NVIM v0.2.2
Latest ActualVim
OSX 10.13.4

**Comment by bkyam** [comment]
I've tried disabling all the packages I've installed. It must be some funky config I have set up. I'll keep poking around and post a solution if I find one. Thanks for getting back to me on this.

**Comment by lunixbochs** [comment]
Try closing Sublime, renaming Application Support/Sublime Text folder, then installing only ActualVim. Could be a config in your user folder.

**Comment by bkyam** [comment]
That didn't seem to work. I ended up finding a workaround by modifying the Sublime Keybindings to have ctrl+y perform a scroll up, rather than 'yank'. That kicked it into gear for me.

Thanks for your support!

**Comment by lunixbochs** [comment]
That's weird. ActualVim should be getting priority because it uses a more specific keybinding context.

**Comment by bkyam** [comment]
I'm going to chalk this up to my funky set up and close this. Thanks again.
