### ISSUE TITLE
Restore SublimeText's Goto Anything/Symbol shortcuts

### ISSUE THREAD

**Issue by darthmall** [lunixbochs/ActualVim#165]
Is there a way to restore access to SublimeText's Goto menus via keyboard shortcuts the default shortcuts for Goto Anything (ctrl-p) and Goto Symbol (ctrl-r) seem to be hijacked by ActualVim, but Goto Symbol in Project (ctrl-shift-p) works fine for me.

**Comment by lunixbochs** [comment]
In actualvim settings, you can define a setting that disables a specific key interception. This is done by adding eg “av:ctrl+p” to one of the settings paths like “mode”: {“normal”: {“av:ctrl+p”: true}}

If you put it under the “vim” settings key it’s disabled anytime vim is active.

**Comment by darthmall** [comment]
Excellent! Is there also a way to disable ActualVim for specific file types? It interferes with SublimeGit. I added

```
{
    "ignored_packages": ["ActualVim"]
}
```

to my `SublimeGit Status.sublime-settings`, but it seems to have no effect.

**Comment by lunixbochs** [comment]
Can you open a new issue for that? I can add ignored file types as a feature.

**Comment by darthmall** [comment]
Done and done: #166

**Comment by adrian-gierakowski** [comment]
Looks like this could be closed
