### ISSUE TITLE
Package doesn't work

### ISSUE THREAD

**Issue by boo1ean** [lunixbochs/actualvim#18]
I am not sublime and I'm not sure if I'm doing things right.

I've just cloned actualvim repo to the `~/.config/sublime-text-3/Packages` and ran sublime and nothing happened.

I guess with successfully installed plugin sublime should have behavior similar to vim: normal mode, insert mode and so on.

Does it have some logs I can check?

Please suggest, Thanks!
- Linux 3.5.0-42-generic #65~precise1-Ubuntu SMP Wed Oct 2 20:57:18 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
- vim 7.3.429
- Sublime Text Build 3047

**Comment by lunixbochs** [comment]
closing in light of #38 - if that doesn't work, you'll need to file a new issue
