### ISSUE TITLE
operators + motions

### ISSUE THREAD

**Issue by tjdevries** [lunixbochs/ActualVim#41]
Hi, really cool plugin!

Just tried using it, and maybe I configured it wrong, but the movement works well and everything but when i try to do something like `cw` while in normal mode, it just inserts the `w`, it does not change the word.

To replicate:

```
my cursor is |here
```

type `cw` in normal mode

```
my cursor is w|here
```

**Comment by lunixbochs** [comment]
That's this upstream issue: https://github.com/neovim/neovim/issues/6166

Syncing the buffer state after you press `c` causes the command to terminate early. I haven't found a workaround yet.

**Comment by lunixbochs** [comment]
can you try the workaround in da39096? for [dyc] (I think those are the only keys that work like this?) I prevent the buffer state from syncing on first press.

**Comment by lunixbochs** [comment]
Status:

3, c, esc, j: Edits the current line like `cc`, then moves down 3 lines.
3, d, j: Deletes one line like `dd`, then moves down 3 lines.
3, y, j: Copies one line like `yy`, then moves down 3 lines.
3, >, j: Indents one line like `>>`, then moves down 3 lines.

There's a pattern here, and I can work around it.

**Comment by lunixbochs** [comment]
This should be mitigated for now on 0.9.10 and neovim 0.2.0 release. We have `neovim_get_mode()` for temporary presses, and I have heuristics to work around all of the broken cases I know about, as long as you haven't remapped keys to broken ones. Can you confirm?

**Comment by tjdevries** [comment]
I'm actually just getting this error and unable to type anything into the buffers:

`ActualVim: request "enter" failed: buf:3 has no view`

**Comment by lunixbochs** [comment]
That's purely a cosmetic error. Do you have an underline cursor?

**Comment by tjdevries** [comment]
Hmmm, so sublime seems to have updated today and the problem went away where I couldn't edit anything.

Now everything seems to work! Thanks for the cool project. Very exciting!
