### ISSUE TITLE
Missing attribute vim in neo module

### ISSUE THREAD

**Issue by x0zzz** [lunixbochs/actualvim#49]
- Mac OS 10.11.6
- Sublime Text Build 3126
- NVIM 0.1.7
- actualvim dff9500.

Console dump:
> reloading settings Packages/User/ActualVim.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 410, in <lambda>
    run_callback(name, vel, lambda: vel.__class__.__dict__[name](vel))
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/actual.py", line 60, in on_activated
    self.v.activate()
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/view.py", line 176, in activate
    neo.vim.force_ready()
AttributeError: 'module' object has no attribute 'vim'

**Comment by lunixbochs** [comment]
Can you restart Sublime Text and make sure there aren't any other errors in the log?

**Comment by x0zzz** [comment]
After update and restart:

> startup, version: 3126 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/j/Library/Application Support/Sublime Text 3/Packages
state path: /Users/j/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/j/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.161351
using gpu buffer for window
first paint time: 0.210124
startup time: 0.211095
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin actualvim.actual
reloading plugin actualvim.edit
reloading plugin actualvim.neo
reloading plugin actualvim.view
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/neo.py", line 45, in plugin_loaded
    vim._setup()
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/neo.py", line 153, in _setup
    self.cmd('set noswapfile')
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/neo.py", line 173, in cmd
    return self.nv.command_output(*args, **kwargs)
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/nvim.py", line 222, in command_output
    return self.request('nvim_command_output', string)
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/msgpack_rpc/session.py", line 106, in request
    v = self._yielding_request(method, args)
  File "/Users/j/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/msgpack_rpc/session.py", line 168, in _yielding_request
    return q.get(timeout=1)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
Unable to fetch update url contents

**Comment by lunixbochs** [comment]
That looks like neovim is hanging on startup. Do you have a neovim rc file?

I've only tested with neovim HEAD (0.20) and 0.16 from homebrew with no vimrc.

If you can do a screen share or at least chat of some kind I can help debug this.

**Comment by justinmk** [comment]
Could be a swapfile dialog (or any other dialog, e.g. a vimrc error). I'll look into that after the API change we discussed.

**Comment by lunixbochs** [comment]
I set noswapfiles (and handle loading/saving through sublime right now), and this is happening on first startup. I didn't think about vimrc and related dialogs. I track the screen state so I can maybe detect this kind of thing heuristically for now and show in an output panel (and also print vim screen state to console if vim ever times out).

**Comment by x0zzz** [comment]
It works after removing init.vim file. I had a link to vim.rc with bunch of plugins and some were complaining at startup, which probably caused the issue.

Btw. I managed to break it again by pressing `ZQ` - I habitually close files this way in gVim ;)
Anyway, thanks for the help. Much appreciated.

**Comment by lunixbochs** [comment]
I'm not sure what to do about quitting neovim. At least I can relaunch it and tell you not to do that as it clears your undo buffer. You also can't save from the vim side yet. It's on my todo.
