### ISSUE TITLE
international key support

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/actualvim#54]
add international keys to key bindings, currently only US ascii is intercepted

**Comment by xelra** [comment]
Wouldn't it make more sense to, instead of capturing specific keys, capture every key and if it's unrecognized, just print it?

**Comment by lunixbochs** [comment]
I don't know of any method in Sublime Text to capture all keys, or I'd do it. Also, in the long run, I want you to still be able to register Sublime Text keyboard shortcuts (though a "sublime mode" would work for that)

**Comment by xelra** [comment]
Maybe somehow autogenerating the keymap from a UTF-8 chartable would be a good solution.

**Comment by lunixbochs** [comment]
Turns out there's a special sublime keymap for `<character>` which triggers on any inserted character.

So, this is fixed in f006b79
