### ISSUE TITLE
Cannot enable ActualVim anymore on Windows

### ISSUE THREAD

**Issue by xelra** [lunixbochs/actualvim#65]
On the perf branch everything works fine. The master doesn't work anymore. Windows 10.

I can't enable ActualVim from the `Ctrl+Shift+P` menu anymore.

It must have happened somewhere between https://github.com/lunixbochs/actualvim/commit/84f682c9195ea48b91e7e986456380ad510bc80a and https://github.com/lunixbochs/actualvim/commit/b6c6b539a6d1278d0e7e11e6a160353dacd3ee06.

EDIT:
LOL, I just saw that you already opened #64.

**Comment by lunixbochs** [comment]
fixed in 1e3e58e
