### ISSUE TITLE
UI trails one keystroke behind.

### ISSUE THREAD

**Issue by jordwalke** [lunixbochs/ActualVim#72]
Occasionally, I will hit a key like `escape`, and the UI won't update to reflect it. Or I might visually select a region, and then hit `c` to change, but the UI doesn't update to show the removed text and cursor in insert mode. It actually is changed in neovim, because the next keystroke (simple up arrow or anything really) will show the change.

**Comment by jordwalke** [comment]
There is nothing in the logs `cmd+backtick`

**Comment by jordwalke** [comment]
This could be a result of some vim setting I have enabled. I'm not sure? Are you aware of any that would effect this?

**Comment by lunixbochs** [comment]
This is almost certainly a result of my heuristics to work around https://github.com/neovim/neovim/issues/6159 - @justinmk's nvim_get_mode neovim PR https://github.com/neovim/neovim/pull/6247 fixes this properly (and improves performance)

**Comment by jordwalke** [comment]
But some vim config setting of mine is causing it because if I remove my vimrc, it doesn't happen. What could it be?

**Comment by lunixbochs** [comment]
It's likely based on lag. If input takes too long, ActualVim will think neovim wasn't ready and not update the screen.

To debug, `print(ready)` at the end of this function (on a new line before `return ret, ready`) and check the sublime console: https://github.com/lunixbochs/actualvim/blob/master/neo.py#L289

**Comment by jordwalke** [comment]
Is there a place where vim errors are logged?

**Comment by jordwalke** [comment]
It was airline!

- It would be good to have a log output of vim errors somewhere.
- It would be good to have a vim setting to be able to check to disable things in my vimrc based on if it's running in Sublime NeoVim.

**Comment by lunixbochs** [comment]
I could `:set` something on ActualVim startup, or expose a function the vimrc can call. Not sure which is more idiomatic.

I'm not sure on the vim errors offhand, but I'll look into it.

**Comment by justinmk** [comment]
`:messages` doesn't work? If not, actualvim could dump it somewhere via `nvim_eval("execute('messages')")`.

**Comment by lunixbochs** [comment]
like `nvim_command('let g:actualvim = true')`?

**Comment by justinmk** [comment]
Yes although in VimL of course it needs to be `1` or `v:true`, not `true`. Or

    nvim_set_var("actualvim", True)

**Comment by lunixbochs** [comment]
I think I need to run this with `--cmd` so it runs before `init.vim`? So

    nvim --embed --cmd "let g:actualvim = v:true"

**Comment by justinmk** [comment]
Yes.

**Comment by lunixbochs** [comment]
@jordwalke 059ee56d0e9ac3b5b257c409db37790728bc089a has `g:actualvim`. If you installed with package control, I think adding `https://github.com/lunixbochs/actualvim` via package control "add repository" will allow you to upgrade to the latest master before I tag a version. Otherwise you can clone directly if you want to test.

**Comment by lunixbochs** [comment]
@jordwalke can you try the async branch on fa6df7e133c51904222acd63203963c5f7216236? This should fix the trailing cursor (but might cause a slight UI lag).

**Comment by lunixbochs** [comment]
This should be completely fixed in tag 0.9.10 with neovim 0.2.0, can you confirm?

**Comment by lunixbochs** [comment]
Closing as this should have been fixed for a while. Reopen if it's still an issue.
