### ISSUE TITLE
Undo (with Neovim) after opening file clears the contents of the file

### ISSUE THREAD

**Issue by evanrelf** [lunixbochs/actualvim#73]
Pressing <kbd>u</kbd> to undo with Neovim (not <kbd>⌘Z</kbd> with Sublime Text) after opening a file will clear the contents of the file and mark the file as modified. This also happens if you've made changes to the file and then undo as far back as possible.

I assume it's because Neovim considers its first state to be a blank buffer, _and then_ Actual injects the contents of the file in Sublime into the buffer. So when you undo after opening a file, Neovim is just undoing the injecting that Actual did.

**Comment by justinmk** [comment]
If @evanrelf's hint is correct this can be avoided by `:setlocal undolevels=-1` to disable undo before injecting the initial contents. Then set it back to the global default via `:setlocal undolevels=-123456` (yes, really), and undo will work normally.

**Comment by lunixbochs** [comment]
Fixed in ea36f15, will be in v0.9.3
