### ISSUE TITLE
Statusline is in Spanish

### ISSUE THREAD

**Issue by carlosvigil** [lunixbochs/ActualVim#77]
<img width="461" alt="screen shot 2017-03-16 at 10 52 01 am" src="https://cloud.githubusercontent.com/assets/18217279/24002244/a05fceb2-0a36-11e7-8b07-2fe9bd136567.png">
<img width="104" alt="screen shot 2017-03-16 at 10 51 44 am" src="https://cloud.githubusercontent.com/assets/18217279/24002246/a06b7e56-0a36-11e7-9c42-3b14b6903eae.png">
<img width="270" alt="screen shot 2017-03-16 at 10 51 14 am" src="https://cloud.githubusercontent.com/assets/18217279/24002245/a063ed12-0a36-11e7-93b1-466b4eb141b2.png">

I've tried removing statusline plugins, i'm not sure how to check Sublime's language, but everything else including plugins in Sublime and Nvim are in English, OS as well. Though, I do have 4 keyboards enabled in my system settings (US, FR, SP, JP) and only US active.

**Comment by lunixbochs** [comment]
Sublime doesn't control the nvim language. If you run nvim on the cmdline, is it in Spanish as well?

**Comment by lunixbochs** [comment]
https://github.com/neovim/neovim/issues/5873 looks like a good starting point for debugging this

**Comment by carlosvigil** [comment]
Nvim has US and utf8 for all.

**Comment by lunixbochs** [comment]
Depending on your OS, Sublime will get a different ENV than your shell.

**Comment by carlosvigil** [comment]
I'll check their forums, thanks!

**Comment by lunixbochs** [comment]
I'm not sure the Sublime forums will help here. It's likely up to the Neovim or ActualVim projects (me!) to debug/fix this.

**Comment by lunixbochs** [comment]
Yeah, env is likely the problem, and Neovim doesn't have a mac language fallback: https://github.com/neovim/neovim/issues/5873#issuecomment-271419931

If you close Sublime and run it from a shell via `/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text` do you get the right language?

**Comment by carlosvigil** [comment]
Yup
<img width="96" alt="screen shot 2017-03-16 at 11 38 51 am" src="https://cloud.githubusercontent.com/assets/18217279/24004617/297aeb90-0a3d-11e7-9682-df349cd9e810.png">

**Comment by lunixbochs** [comment]
Will work on a fix. For now, maybe add `"--cmd", "lang en_US"` to the "neovim_args" in your ActualVim settings

**Comment by lunixbochs** [comment]
This should be fixed in the latest version of Sublime Text 3, which supposedly loads a real shell environment.

**Comment by lunixbochs** [comment]
Can you confirm this is fixed in the latest Sublime Text 3 build?

**Comment by carlosvigil** [comment]
3126? Fresh install not fixed.

**Comment by carlosvigil** [comment]
This is fixed in 3148. Have not tested previous versions down to 3126.

**Comment by lunixbochs** [comment]
That's good enough, thanks for the update.

**Comment by carlosvigil** [comment]
Sorry to bring it up again, it was working well when my OS language was French. Went back to US and the status line is Spanish. Since it might be suspicious, I don't usually switch languages nor have I used Spanish.

**Comment by lunixbochs** [comment]
ActualVim shouldn't really be doing anything to affect this. If it works in your shell, Sublime isn't copying your shell env correctly. If it doesn't work in your shell, Neovim is the culprit.
