### ISSUE TITLE
Error loading colour scheme Packages/actualvim/Bell.tmTheme: Unable to open Packages/actualvim/Bell.tmTheme

### ISSUE THREAD

**Issue by amritk** [lunixbochs/ActualVim#87]
Every time I hit escape I get this error 
Error loading colour scheme Packages/actualvim/Bell.tmTheme: Unable to open Packages/actualvim/Bell.tmTheme

Running Ubuntu 16.04 with Build 3126

**Comment by lunixbochs** [comment]
Package Control?

**Comment by amritk** [comment]
ah yes I did, cheers!

**Comment by lunixbochs** [comment]
This is still broken, that's just a workaround. Thanks for pointing it out. I'll need to think about how to properly fix this.

**Comment by lunixbochs** [comment]
I renamed the package from actualvim to ActualVim and changed the default setting. Anyone on a case-sensitive filesystem who has tweaked their settings will need to update the bell setting from `actualvim` -> `ActualVim` manually.
