### ISSUE TITLE
<c-[> doesn't work to get back to normal mode

### ISSUE THREAD

**Issue by donut** [lunixbochs/ActualVim#92]
When I'm in any mode aside from visual I'm accustomed to being able to hit <kbd>c</kbd>-<kbd>[</kbd> to get back to normal mode. This works in `vi`, `vim`, `nvim`, and various other vi(m) modes in other editors. Am I missing something?

```
Sublime Text Build 3129
macOS 10.12.4
↪ nvim --version                                                     0@10:50:27
NVIM 0.1.7
Build type: RelWithDebInfo
```

**Comment by lunixbochs** [comment]
Works for me. Build 3126, NVIM v0.2.0-624-gddab466, macOS 10.12.4.

Are you 100% sure it's not going back to normal mode? Try pressing <kbd>c-[</kbd> then a normal mode command such as <kbd>dd</kbd>. If this works, you might be running into lag in the update heuristic:

- #91
- #72
- #41
- https://github.com/neovim/neovim/issues/6159

Neovim can currently deadlock Sublime. I work around it with a heuristic with no false positives (so no deadlocks), but some false negatives. When you get a false negative, the UI will occasionally not update.

The status line is also not guaranteed to update (race condition). I'll open a separate issue for that.

**Comment by donut** [comment]
~~Hitting <kbd>i c-[ dd</kbd> just results in printing out "dd".~~ Never mind, I just realized I had set a Sublime Text keybinding for <kbd>c-[</kbd> to Vintageous' return to normal mode command. Sorry for wasting your time.

**Comment by lunixbochs** [comment]
You could try adding a context like this if you want to keep the keybinding:

    { "keys": ["ctrl+["], "context": [{ "key": "setting.actual_mode", "operand": false }], "command": "whatever" },

**Comment by donut** [comment]
Since I'm not using Vintageous anymore, I just removed the keybinding and <kbd>c-[</kbd> started working with ActualVim. Thanks!
